blueprint:
  name: "Pulizie Automation Blueprint"
  description: >-
    Blueprint per gestire un singolo task di pulizia mattutina o serale (in casa/fuori) con script.pulisci_stanza.
  domain: automation
  input:
    morning_time:
      name: "Orario pulizia mattutina"
      selector:
        time: {}
    evening_time:
      name: "Orario pulizia serale"
      selector:
        time: {}
    days_morning:
      name: "Giorni pulizia mattutina"
      selector:
        select:
          options:
            - lunedì
            - martedì
            - mercoledì
            - giovedì
            - venerdì
            - sabato
            - domenica
          multiple: true
    days_evening:
      name: "Giorni pulizia serale"
      selector:
        select:
          options:
            - lunedì
            - martedì
            - mercoledì
            - giovedì
            - venerdì
            - sabato
            - domenica
          multiple: true
    cleaned_boolean:
      name: "Flag pulizia effettuata"
      selector:
        entity:
          domain: input_boolean
    vacuum_sensor:
      name: "Sensore stato robot"
      selector:
        entity:
          domain: sensor
    end_states:
      name: "Stati fine pulizia"
      description: "Stati del sensore che indicano che il robot ha terminato"
      selector:
        select:
          options:
            - idle
            - sleeping
            - charging
          multiple: true
    away_counter:
      name: "Contatore away/home"
      description: "1 = fuori casa"
      selector:
        entity:
          domain: counter
    morning_segment:
      name: "Segment ID mattino"
      selector:
        number: {}
    morning_type:
      name: "Tipo pulizia mattino"
      selector:
        select:
          options:
            - aspirazione
            - lavaggio
            - genius
            - genius_deep
    evening_segment:
      name: "Segment ID sera"
      selector:
        number: {}
    evening_type:
      name: "Tipo pulizia sera"
      selector:
        select:
          options:
            - aspirazione
            - lavaggio
            - genius
            - genius_deep
    away_segment:
      name: "Segment ID sera (fuori)"
      selector:
        number: {}
    away_type:
      name: "Tipo pulizia sera (fuori)"
      selector:
        select:
          options:
            - aspirazione
            - lavaggio
            - genius
            - genius_deep
trigger:
  - platform: time
    at: !input morning_time
    id: morning
  - platform: time
    at: !input evening_time
    id: evening
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.id == 'morning'
                 and now().strftime('%A').lower() in
                     (input.days_morning | map('lower') | list)
                 and is_state(input.cleaned_boolean, 'off') }}
        sequence:
          - service: script.turn_on
            target:
              entity_id: script.pulisci_stanza
            data:
              variables:
                segment_id: "{{ input.morning_segment }}"
                tipo_pulizia: "{{ input.morning_type }}"
          - wait_for_trigger:
              - platform: state
                entity_id: !input vacuum_sensor
                to: "idle"
              - platform: state
                entity_id: !input vacuum_sensor
                to: "sleeping"
              - platform: state
                entity_id: !input vacuum_sensor
                to: "charging"
          - service: input_boolean.turn_on
            target:
              entity_id: !input cleaned_boolean
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.id == 'evening'
                 and now().strftime('%A').lower() in
                     (input.days_evening | map('lower') | list) }}
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input away_counter
                    state: '1'
                sequence:
                  - service: script.turn_on
                    target:
                      entity_id: script.pulisci_stanza
                    data:
                      variables:
                        segment_id: "{{ input.away_segment }}"
                        tipo_pulizia: "{{ input.away_type }}"
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input vacuum_sensor
                        to: "idle"
                      - platform: state
                        entity_id: !input vacuum_sensor
                        to: "sleeping"
                      - platform: state
                        entity_id: !input vacuum_sensor
                        to: "charging"
              - default:
                  - service: script.turn_on
                    target:
                      entity_id: script.pulisci_stanza
                    data:
                      variables:
                        segment_id: "{{ input.evening_segment }}"
                        tipo_pulizia: "{{ input.evening_type }}"
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input vacuum_sensor
                        to: "idle"
                      - platform: state
                        entity_id: !input vacuum_sensor
                        to: "sleeping"
                      - platform: state
                        entity_id: !input vacuum_sensor
                        to: "charging"
          - service: input_boolean.turn_on
            target:
              entity_id: !input cleaned_boolean
mode: single
