blueprint:
  name: "Blueprint Pulizie Mattina e Sera"
  description: >-
    Blueprint per automazione pulizie mattina e sera con chiamata a script.pulisci_stanza.
  domain: automation
  input:
    morning_time:
      name: "Orario pulizia mattutina"
      selector:
        time: {}
    evening_time:
      name: "Orario pulizia serale"
      selector:
        time: {}
    days_morning:
      name: "Giorni pulizia mattutina"
      selector:
        select:
          options:
            - lunedì
            - martedì
            - mercoledì
            - giovedì
            - venerdì
            - sabato
            - domenica
          multiple: true
    days_evening:
      name: "Giorni pulizia serale"
      selector:
        select:
          options:
            - lunedì
            - martedì
            - mercoledì
            - giovedì
            - venerdì
            - sabato
            - domenica
          multiple: true
    cleaned_today:
      name: "Flag pulita oggi"
      selector:
        entity:
          domain: input_boolean
    vacuum_sensor:
      name: "Sensore stato robot"
      selector:
        entity:
          domain: sensor
    end_states:
      name: "Stati fine pulizia"
      description: "Stati del sensore che indicano la fine del ciclo"
      selector:
        select:
          options:
            - idle
            - sleeping
            - charging
          multiple: true
    away_counter:
      name: "Contatore away/home"
      description: "1 = fuori casa"
      selector:
        entity:
          domain: counter
    morning_segment_id:
      name: "Segment ID mattino"
      selector:
        number:
          min: 1
          max: 999
          step: 1
    morning_clean_type:
      name: "Tipo pulizia mattino"
      selector:
        select:
          options:
            - aspirazione
            - lavaggio
            - genius
            - genius_deep
    evening_segment_id:
      name: "Segment ID sera"
      selector:
        number:
          min: 1
          max: 999
          step: 1
    evening_clean_type:
      name: "Tipo pulizia sera"
      selector:
        select:
          options:
            - aspirazione
            - lavaggio
            - genius
            - genius_deep
    away_segment_id:
      name: "Segment ID sera (fuori)"
      selector:
        number:
          min: 1
          max: 999
          step: 1
    away_clean_type:
      name: "Tipo pulizia sera (fuori)"
      selector:
        select:
          options:
            - aspirazione
            - lavaggio
            - genius
            - genius_deep
trigger:
  - id: morning
    platform: time
    at: !input morning_time
  - id: evening
    platform: time
    at: !input evening_time
condition: []
action:
  - choose:
      # Mattina
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.id == 'morning'
                 and now().strftime('%A').lower() in
                   (input.days_morning | map('lower') | list)
                 and is_state(input.cleaned_today, 'off') }}
        sequence:
          - service: script.turn_on
            target:
              entity_id: script.pulisci_stanza
            data:
              variables:
                segment_id: "{{ input.morning_segment_id }}"
                tipo_pulizia: "{{ input.morning_clean_type }}"
          - wait_template: >-
              {{ states[input.vacuum_sensor].state in input.end_states }}
          - service: input_boolean.turn_on
            target:
              entity_id: !input cleaned_today
      # Sera
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.id == 'evening'
                 and now().strftime('%A').lower() in
                   (input.days_evening | map('lower') | list) }}
        sequence:
          - choose:
              # Fuori casa
              - conditions:
                  - condition: state
                    entity_id: !input away_counter
                    state: '1'
                sequence:
                  - service: script.turn_on
                    target:
                      entity_id: script.pulisci_stanza
                    data:
                      variables:
                        segment_id: "{{ input.away_segment_id }}"
                        tipo_pulizia: "{{ input.away_clean_type }}"
                  - wait_template: >-
                      {{ states[input.vacuum_sensor].state in input.end_states }}
              # In casa (default)
              - default:
                  - service: script.turn_on
                    target:
                      entity_id: script.pulisci_stanza
                    data:
                      variables:
                        segment_id: "{{ input.evening_segment_id }}"
                        tipo_pulizia: "{{ input.evening_clean_type }}"
                  - wait_template: >-
                      {{ states[input.vacuum_sensor].state in input.end_states }}
          - service: input_boolean.turn_on
            target:
              entity_id: !input cleaned_today
mode: single
